version: 2
jobs:
  lint:
    docker:
      # TODO: Replace with our own CI image
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: PYTHON_FILES_CHANGED=$(git diff --name-only ${CIRCLE_SHA1} -- '*.py')
      - run: if [ ! -z ${PYTHON_FILES_CHANGED} ]; then flake8 ${PYTHON_FILES_CHANGED} && isort --check-only ${PYTHON_FILES_CHANGED}; fi;
      - run: JS_FILES_CHANGED=$(git diff --name-only ${DRONE_COMMIT_SHA} -- '*.js' '*.jsx')
      - run: if [ ! -z ${PYTHON_FILES_CHANGED} ]; then eslint ${JS_FILES_CHANGED}; fi;
      # Artifacts?

  backend_test:
    machine: true
    # DLC?
    steps:
      - checkout
      - run: docker-compose run web ./manage.py test

  frontend_test:
    docker:
      # TODO: Replace with our own CI image
      - image: circleci/python:3.7
    steps:
      # Yarn first?
      # - run: yarn test
      - run: echo "yarn test here"

  deploy:
    docker:
      # TODO: Replace with our own CI image
      - image: circleci/python:3.7
    steps:
      - run: echo "To be continued..."

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - backend_test
      - frontend_test
      - lint
      - deploy:
        requires:
          - backend_test
          - frontend_test
          - lint
